apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: linkding
  name: linkding
  namespace: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: linkding
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 3000
      containers:
      - image: sissbruecker/linkding:latest
        name: linkding
        volumeMounts:
        - mountPath: /etc/linkding/data
          name: test-vol
        ports:
        - containerPort: 9090

        securityContext:
          allowPrivilegeEscalation: false # Disable privilege escalation
          capabilities:
            drop: ["ALL"] # Drop all capabilities

      volumes:
      - name: test-vol
        persistentVolumeClaim: 
          claimName: linkding-volume-pvc
status: {}
